### PR TITLE
Support dark style preference

### LINKED ISSUE #94: Follow dark style preference
I think Sideload would be considered part of the system, since it's not launchable on its own.

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #94

### CODE REVIEW

**Comment by 4jNsY6fCVqZv** [comment]
Btw. Does this solution also work for third-party apps?

**Comment by 4jNsY6fCVqZv** [comment]
Besides, does this solution also work for third-party apps?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv yes, it is just using the Granite utility. We will likely write documentation on how third-party apps can support a dark style preference once we're closer to the release.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Thanks for documenting this!
If I want to implement these changes into the code of a third-party app right now, do I need a separate development branch because otherwise an app version that depends on Granite >=5.4.0 will probably not run on Hera systems anymore?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv I believe we released that granite update to Hera, and if an app does this on Hera, it will silently fail and continue to work as before. For example, WingPanel and Switchboard have this code in Hera as well.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Thanks again!

**Pull request merged**
