### PR TITLE
Auto add remotes

### LINKED ISSUE #13: App gets stuck when a runtime is missing
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When installing an app from flathub on a fresh installation of Juno, a warning appears in the terminal about a missing runtime, and the app gets stuck at around 1% progress.

### To Reproduce
1. Install a fresh operating system (with no flatpaks etc.)
2. Install any app from flathub

### Expected behavior

Sideload automatically installs the runtime, and the app installation succeeds.

### Screenshots or screen recordings

platform

### Logs
```
jlnr@Workstation:~/Projects/sideload/build$ io.elementary.sideload '/home/jlnr/Downloads/com.slack.Slack.flatpakref' 

** (io.elementary.sideload:2465): WARNING **: 00:40:16.564: MainWindow.vala:131: The application com.slack.Slack/x86_64/stable requires the runtime org.freedesktop.Platform/x86_64/19.08 which was not found
```

## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #13 

`.flatpakref` files can specify a remote that contains their runtime deps. The `flatpak` cli tool asks the user if they wish to add these and if they wish to allow the installation of each runtime.

But since we've already thrown a dialog along the lines of this hasn't been vetted, be sure you trust it, etc... I *think* we're OK to just let sideload auto accept the addition of remotes that the ref file states are necessary for runtimes?

Thoughts?

### CODE REVIEW

**Comment by davidmhewitt** [comment]
Worth pointing out that the other possible `TransactionRemoteReason` that I'm currently rejecting in this code is some functionality that lets the `.flatpakref` have a section to say the remote is a generic store type remote with other apps in it, so would you like to keep it in case you want other apps from there. Since sideload is only designed for sideloading a single app, I thought it best to reject those remotes.

That said, the first time you load anything from flathub, it'll likely add the flathub remote anyway as that'll have the runtime deps.

**Comment by cassidyjames** [comment]
I think it makes sense that sideloading something from Flathub would enable the Flathub remote… unless we can only enable a specific app from a remote (and not break when sideloading _another_ app from that remote). But I do think we need to add copy to the first consent screen mentioning that it might add a repository of other apps to your system or something.

**Comment by cassidyjames** [comment]
Something like this?

>### Install untrusted software?
>
>This software is provided solely by its developer and has not been reviewed for security, privacy, or system integration. Installing this software may add a repository of other apps that will show up in AppCenter.
>
> :black_square_button: I understand
>
> `Cancel`    **`Install`**

**Comment by davidmhewitt** [comment]
Yeah, I don't think it's really feasible to only install an app and its runtimes from flathub (or wherever) without ending up with the rest of the apps on the remote left available. I'm not sure if it's possible to remove a remote once you've installed stuff from it, but if so, you'd be leaving the runtimes without the possibility of updates. So I think that adding that copy is the way forwards.

**Pull request merged**
